### PR TITLE
feat: display more context on binary exit

### LINKED ISSUE #110: Display more context on exit error
When process exit unexpected, gtctl will print an error like `binary '/path/to/greptimedb-dev/debug/greptime' exited with error: exit status 1`

But all three components are in this binary, I cannot figure out which component is wrong (especially when their log doesn't contains relative information). It would be better if we could also see some extra context, like the command of this binary, or the last 5 lines of logs, etc.

### PR DESCRIPTION
**Pull request by waynexia**
closes #110 

Two changes:
- change pid from pid file to the real pid
- display pid and start args on exit

### CODE REVIEW

**Comment by waynexia** [comment]
It now looks like
image

**Review by shawnh2 — APPROVED** [review]
LGTM. can merge it right now.

notice: when you exit the gtctl, the cluster (include log file) will also be deleted. so for those users who want the logs remain, consider add a `RetainLogs` option for bare-metal mode. I'm working on this right now.

**Comment by waynexia** [comment]
>notice: when you exit the gtctl, the cluster (include log file) will also be deleted. so for those users who want the logs remain, consider add a RetainLogs option for bare-metal mode. I'm working on this right now.

Just run into this problem lol

**Review by zyy17 — APPROVED** [review]
Can't believe you become the Gopher 😊

**Pull request merged**
