### PR TITLE
chore: remove opentsdb addr

### PR DESCRIPTION
**Pull request by confoc**
In the new version, OpentsdbAddr is not used.
So,I delete the OpentsdbAddr  in order to run gtctl correctly

### CODE REVIEW

**Comment by daviderli614** [comment]
@confoc Delete here: https://github.com/GreptimeTeam/gtctl/blob/develop/pkg/helm/testdata/db-manifests.yaml#L36

**Comment by zyy17** [comment]
@daviderli614 After the PR is merged, we need to release the new version.

**Review by daviderli614 — APPROVED** [review]
LGTM

**Review by zyy17 — APPROVED** [review]
Thank you for your first PR in Greptime🎉

**Pull request merged**
