### PR TITLE
refactor: separate cluster connect cmd from its implementation logic

### PR DESCRIPTION
**Pull request by shawnh2**
separate gtctl cmd from its implementation logic, this PR only separate `cluster connect` cmd. 

others will be done in the following PRs.

related to: #160

### CODE REVIEW

**Comment by zyy17** [comment]
IMHO, I feel that the two approaches are more about style differences, but this approach seems to separate the specific usage points of the method into `cmd/gtctl`, so it can look cleaner. Let's try your way.

**Comment by zyy17** [comment]
The PR title seems OK, but why the CI always failed?

**Comment by shawnh2** [comment]
> The PR title seems OK, but why the CI always failed?

there is something wrong with current ci, will be fixed in #163

**Review by zyy17 — APPROVED** [review]
lgtm

**Pull request merged**
